version: 0.2

phases:
  install:
    commands:
      - npm install
      - npm run build
      - aws s3 cp build s3://arn:aws:s3:::maks-ui-dev
      - aws s3 cp build/* s3://arn:aws:s3:::maks-ui-dev
artifacts:
  files:
    - '**/*'