version: 0.2

phases:
  install:
    commands:
      - npm install
      - npm run build
      - aws s3 cp build s3://maks-ui-dev
      - aws s3 cp build/index.html s3://maks-ui-dev
artifacts:
  files:
    - '**/*'